//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMailService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendMailService.SendMailServiceSoap")]
    public interface SendMailServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailNotice", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendMailNoticeResponse> SendMailNoticeAsync(SendMailService.SendMailNoticeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendMailResponse> SendMailAsync(SendMailService.SendMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailSmtpAuthentication", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendMailSmtpAuthenticationResponse> SendMailSmtpAuthenticationAsync(SendMailService.SendMailSmtpAuthenticationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SimplifySendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SimplifySendMailResponse> SimplifySendMailAsync(SendMailService.SimplifySendMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailInsertQueue", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendEmailInsertQueueResponse> SendEmailInsertQueueAsync(SendMailService.SendEmailInsertQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMobileNotice", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendMobileNoticeResponse> SendMobileNoticeAsync(SendMailService.SendMobileNoticeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSNotice", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendSMSNoticeResponse> SendSMSNoticeAsync(SendMailService.SendSMSNoticeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSByPhoneID", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendSMSByPhoneIDResponse> SendSMSByPhoneIDAsync(SendMailService.SendSMSByPhoneIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSByPhoneIDOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendSMSByPhoneIDOrderResponse> SendSMSByPhoneIDOrderAsync(SendMailService.SendSMSByPhoneIDOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSByEmployeeID", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendSMSByEmployeeIDResponse> SendSMSByEmployeeIDAsync(SendMailService.SendSMSByEmployeeIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSByEmployeeIDOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendSMSByEmployeeIDOrderResponse> SendSMSByEmployeeIDOrderAsync(SendMailService.SendSMSByEmployeeIDOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendUnicomSMSByPhoneID", ReplyAction="*")]
        System.Threading.Tasks.Task<SendMailService.SendUnicomSMSByPhoneIDResponse> SendUnicomSMSByPhoneIDAsync(SendMailService.SendUnicomSMSByPhoneIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailNoticeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailNotice", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendMailNoticeRequestBody Body;
        
        public SendMailNoticeRequest()
        {
        }
        
        public SendMailNoticeRequest(SendMailService.SendMailNoticeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailNoticeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string From;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Body;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool IsBodyHtml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Attachments;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Password;
        
        public SendMailNoticeRequestBody()
        {
        }
        
        public SendMailNoticeRequestBody(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password)
        {
            this.Site = Site;
            this.TeamPwd = TeamPwd;
            this.From = From;
            this.To = To;
            this.Cc = Cc;
            this.Bcc = Bcc;
            this.Subject = Subject;
            this.Body = Body;
            this.IsBodyHtml = IsBodyHtml;
            this.Attachments = Attachments;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailNoticeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailNoticeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendMailNoticeResponseBody Body;
        
        public SendMailNoticeResponse()
        {
        }
        
        public SendMailNoticeResponse(SendMailService.SendMailNoticeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailNoticeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMailNoticeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LogID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage;
        
        public SendMailNoticeResponseBody()
        {
        }
        
        public SendMailNoticeResponseBody(bool SendMailNoticeResult, string LogID, string ErrorMessage)
        {
            this.SendMailNoticeResult = SendMailNoticeResult;
            this.LogID = LogID;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMail", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendMailRequestBody Body;
        
        public SendMailRequest()
        {
        }
        
        public SendMailRequest(SendMailService.SendMailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool IsBodyHtml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string From;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Attachments;
        
        public SendMailRequestBody()
        {
        }
        
        public SendMailRequestBody(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments)
        {
            this.TeamPwd = TeamPwd;
            this.IsBodyHtml = IsBodyHtml;
            this.From = From;
            this.To = To;
            this.Cc = Cc;
            this.Bcc = Bcc;
            this.Subject = Subject;
            this.Body = Body;
            this.Attachments = Attachments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendMailResponseBody Body;
        
        public SendMailResponse()
        {
        }
        
        public SendMailResponse(SendMailService.SendMailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMailResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mgs;
        
        public SendMailResponseBody()
        {
        }
        
        public SendMailResponseBody(bool SendMailResult, string Mgs)
        {
            this.SendMailResult = SendMailResult;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailSmtpAuthenticationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailSmtpAuthentication", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendMailSmtpAuthenticationRequestBody Body;
        
        public SendMailSmtpAuthenticationRequest()
        {
        }
        
        public SendMailSmtpAuthenticationRequest(SendMailService.SendMailSmtpAuthenticationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailSmtpAuthenticationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool IsBodyHtml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string From;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Body;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Attachments;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Password;
        
        public SendMailSmtpAuthenticationRequestBody()
        {
        }
        
        public SendMailSmtpAuthenticationRequestBody(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments, string UserName, string Password)
        {
            this.TeamPwd = TeamPwd;
            this.IsBodyHtml = IsBodyHtml;
            this.From = From;
            this.To = To;
            this.Cc = Cc;
            this.Bcc = Bcc;
            this.Subject = Subject;
            this.Body = Body;
            this.Attachments = Attachments;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailSmtpAuthenticationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailSmtpAuthenticationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendMailSmtpAuthenticationResponseBody Body;
        
        public SendMailSmtpAuthenticationResponse()
        {
        }
        
        public SendMailSmtpAuthenticationResponse(SendMailService.SendMailSmtpAuthenticationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailSmtpAuthenticationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMailSmtpAuthenticationResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mgs;
        
        public SendMailSmtpAuthenticationResponseBody()
        {
        }
        
        public SendMailSmtpAuthenticationResponseBody(bool SendMailSmtpAuthenticationResult, string Mgs)
        {
            this.SendMailSmtpAuthenticationResult = SendMailSmtpAuthenticationResult;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SimplifySendMailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SimplifySendMail", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SimplifySendMailRequestBody Body;
        
        public SimplifySendMailRequest()
        {
        }
        
        public SimplifySendMailRequest(SendMailService.SimplifySendMailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SimplifySendMailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool IsHtml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FromAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ToAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Body;
        
        public SimplifySendMailRequestBody()
        {
        }
        
        public SimplifySendMailRequestBody(string TeamPwd, bool IsHtml, string FromAddress, string ToAddress, string Subject, string Body)
        {
            this.TeamPwd = TeamPwd;
            this.IsHtml = IsHtml;
            this.FromAddress = FromAddress;
            this.ToAddress = ToAddress;
            this.Subject = Subject;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SimplifySendMailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SimplifySendMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SimplifySendMailResponseBody Body;
        
        public SimplifySendMailResponse()
        {
        }
        
        public SimplifySendMailResponse(SendMailService.SimplifySendMailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SimplifySendMailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SimplifySendMailResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mgs;
        
        public SimplifySendMailResponseBody()
        {
        }
        
        public SimplifySendMailResponseBody(bool SimplifySendMailResult, string Mgs)
        {
            this.SimplifySendMailResult = SimplifySendMailResult;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailInsertQueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailInsertQueue", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendEmailInsertQueueRequestBody Body;
        
        public SendEmailInsertQueueRequest()
        {
        }
        
        public SendEmailInsertQueueRequest(SendMailService.SendEmailInsertQueueRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailInsertQueueRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string From;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Bcc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Body;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool IsBodyHtml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Attachments;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Password;
        
        public SendEmailInsertQueueRequestBody()
        {
        }
        
        public SendEmailInsertQueueRequestBody(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password)
        {
            this.Site = Site;
            this.TeamPwd = TeamPwd;
            this.From = From;
            this.To = To;
            this.Cc = Cc;
            this.Bcc = Bcc;
            this.Subject = Subject;
            this.Body = Body;
            this.IsBodyHtml = IsBodyHtml;
            this.Attachments = Attachments;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEmailInsertQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEmailInsertQueueResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendEmailInsertQueueResponseBody Body;
        
        public SendEmailInsertQueueResponse()
        {
        }
        
        public SendEmailInsertQueueResponse(SendMailService.SendEmailInsertQueueResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEmailInsertQueueResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEmailInsertQueueResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage;
        
        public SendEmailInsertQueueResponseBody()
        {
        }
        
        public SendEmailInsertQueueResponseBody(bool SendEmailInsertQueueResult, string ErrorMessage)
        {
            this.SendEmailInsertQueueResult = SendEmailInsertQueueResult;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMobileNoticeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMobileNotice", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendMobileNoticeRequestBody Body;
        
        public SendMobileNoticeRequest()
        {
        }
        
        public SendMobileNoticeRequest(SendMailService.SendMobileNoticeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMobileNoticeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FromEmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ToEmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Body;
        
        public SendMobileNoticeRequestBody()
        {
        }
        
        public SendMobileNoticeRequestBody(string Site, string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body)
        {
            this.Site = Site;
            this.TeamPwd = TeamPwd;
            this.FromEmployeeID = FromEmployeeID;
            this.ToEmployeeID = ToEmployeeID;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMobileNoticeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMobileNoticeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendMobileNoticeResponseBody Body;
        
        public SendMobileNoticeResponse()
        {
        }
        
        public SendMobileNoticeResponse(SendMailService.SendMobileNoticeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMobileNoticeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMobileNoticeResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LogID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessage;
        
        public SendMobileNoticeResponseBody()
        {
        }
        
        public SendMobileNoticeResponseBody(bool SendMobileNoticeResult, string LogID, string ErrorMessage)
        {
            this.SendMobileNoticeResult = SendMobileNoticeResult;
            this.LogID = LogID;
            this.ErrorMessage = ErrorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSNoticeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSNotice", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSNoticeRequestBody Body;
        
        public SendSMSNoticeRequest()
        {
        }
        
        public SendSMSNoticeRequest(SendMailService.SendSMSNoticeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSNoticeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FromEmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ToEmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Body;
        
        public SendSMSNoticeRequestBody()
        {
        }
        
        public SendSMSNoticeRequestBody(string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body)
        {
            this.TeamPwd = TeamPwd;
            this.FromEmployeeID = FromEmployeeID;
            this.ToEmployeeID = ToEmployeeID;
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSNoticeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSNoticeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSNoticeResponseBody Body;
        
        public SendSMSNoticeResponse()
        {
        }
        
        public SendSMSNoticeResponse(SendMailService.SendSMSNoticeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSNoticeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMSNoticeResult;
        
        public SendSMSNoticeResponseBody()
        {
        }
        
        public SendSMSNoticeResponseBody(bool SendSMSNoticeResult)
        {
            this.SendSMSNoticeResult = SendSMSNoticeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSByPhoneIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSByPhoneID", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSByPhoneIDRequestBody Body;
        
        public SendSMSByPhoneIDRequest()
        {
        }
        
        public SendSMSByPhoneIDRequest(SendMailService.SendSMSByPhoneIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSByPhoneIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SMSContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Mgs;
        
        public SendSMSByPhoneIDRequestBody()
        {
        }
        
        public SendSMSByPhoneIDRequestBody(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string Mgs)
        {
            this.Site = Site;
            this.Unit = Unit;
            this.TeamPwd = TeamPwd;
            this.PhoneID = PhoneID;
            this.SMSContent = SMSContent;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSByPhoneIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSByPhoneIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSByPhoneIDResponseBody Body;
        
        public SendSMSByPhoneIDResponse()
        {
        }
        
        public SendSMSByPhoneIDResponse(SendMailService.SendSMSByPhoneIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSByPhoneIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMSByPhoneIDResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mgs;
        
        public SendSMSByPhoneIDResponseBody()
        {
        }
        
        public SendSMSByPhoneIDResponseBody(bool SendSMSByPhoneIDResult, string Mgs)
        {
            this.SendSMSByPhoneIDResult = SendSMSByPhoneIDResult;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSByPhoneIDOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSByPhoneIDOrder", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSByPhoneIDOrderRequestBody Body;
        
        public SendSMSByPhoneIDOrderRequest()
        {
        }
        
        public SendSMSByPhoneIDOrderRequest(SendMailService.SendSMSByPhoneIDOrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSByPhoneIDOrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SMSContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OrderTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Mgs;
        
        public SendSMSByPhoneIDOrderRequestBody()
        {
        }
        
        public SendSMSByPhoneIDOrderRequestBody(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string OrderTime, string Mgs)
        {
            this.Site = Site;
            this.Unit = Unit;
            this.TeamPwd = TeamPwd;
            this.PhoneID = PhoneID;
            this.SMSContent = SMSContent;
            this.OrderTime = OrderTime;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSByPhoneIDOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSByPhoneIDOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSByPhoneIDOrderResponseBody Body;
        
        public SendSMSByPhoneIDOrderResponse()
        {
        }
        
        public SendSMSByPhoneIDOrderResponse(SendMailService.SendSMSByPhoneIDOrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSByPhoneIDOrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMSByPhoneIDOrderResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mgs;
        
        public SendSMSByPhoneIDOrderResponseBody()
        {
        }
        
        public SendSMSByPhoneIDOrderResponseBody(bool SendSMSByPhoneIDOrderResult, string Mgs)
        {
            this.SendSMSByPhoneIDOrderResult = SendSMSByPhoneIDOrderResult;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSByEmployeeIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSByEmployeeID", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSByEmployeeIDRequestBody Body;
        
        public SendSMSByEmployeeIDRequest()
        {
        }
        
        public SendSMSByEmployeeIDRequest(SendMailService.SendSMSByEmployeeIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSByEmployeeIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ToEmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SMSContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Mgs;
        
        public SendSMSByEmployeeIDRequestBody()
        {
        }
        
        public SendSMSByEmployeeIDRequestBody(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string Mgs)
        {
            this.Site = Site;
            this.Unit = Unit;
            this.TeamPwd = TeamPwd;
            this.ToEmployeeID = ToEmployeeID;
            this.SMSContent = SMSContent;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSByEmployeeIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSByEmployeeIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSByEmployeeIDResponseBody Body;
        
        public SendSMSByEmployeeIDResponse()
        {
        }
        
        public SendSMSByEmployeeIDResponse(SendMailService.SendSMSByEmployeeIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSByEmployeeIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMSByEmployeeIDResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mgs;
        
        public SendSMSByEmployeeIDResponseBody()
        {
        }
        
        public SendSMSByEmployeeIDResponseBody(bool SendSMSByEmployeeIDResult, string Mgs)
        {
            this.SendSMSByEmployeeIDResult = SendSMSByEmployeeIDResult;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSByEmployeeIDOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSByEmployeeIDOrder", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSByEmployeeIDOrderRequestBody Body;
        
        public SendSMSByEmployeeIDOrderRequest()
        {
        }
        
        public SendSMSByEmployeeIDOrderRequest(SendMailService.SendSMSByEmployeeIDOrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSByEmployeeIDOrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Unit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ToEmployeeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SMSContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string OrderTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Mgs;
        
        public SendSMSByEmployeeIDOrderRequestBody()
        {
        }
        
        public SendSMSByEmployeeIDOrderRequestBody(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string OrderTime, string Mgs)
        {
            this.Site = Site;
            this.Unit = Unit;
            this.TeamPwd = TeamPwd;
            this.ToEmployeeID = ToEmployeeID;
            this.SMSContent = SMSContent;
            this.OrderTime = OrderTime;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSByEmployeeIDOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSByEmployeeIDOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendSMSByEmployeeIDOrderResponseBody Body;
        
        public SendSMSByEmployeeIDOrderResponse()
        {
        }
        
        public SendSMSByEmployeeIDOrderResponse(SendMailService.SendSMSByEmployeeIDOrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSByEmployeeIDOrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendSMSByEmployeeIDOrderResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mgs;
        
        public SendSMSByEmployeeIDOrderResponseBody()
        {
        }
        
        public SendSMSByEmployeeIDOrderResponseBody(bool SendSMSByEmployeeIDOrderResult, string Mgs)
        {
            this.SendSMSByEmployeeIDOrderResult = SendSMSByEmployeeIDOrderResult;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUnicomSMSByPhoneIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUnicomSMSByPhoneID", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendUnicomSMSByPhoneIDRequestBody Body;
        
        public SendUnicomSMSByPhoneIDRequest()
        {
        }
        
        public SendUnicomSMSByPhoneIDRequest(SendMailService.SendUnicomSMSByPhoneIDRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendUnicomSMSByPhoneIDRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TeamName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TeamPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Unit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SMSContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LogID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Mgs;
        
        public SendUnicomSMSByPhoneIDRequestBody()
        {
        }
        
        public SendUnicomSMSByPhoneIDRequestBody(string Site, string TeamName, string TeamPwd, string Unit, string PhoneID, string SMSContent, string LogID, string Key, string Mgs)
        {
            this.Site = Site;
            this.TeamName = TeamName;
            this.TeamPwd = TeamPwd;
            this.Unit = Unit;
            this.PhoneID = PhoneID;
            this.SMSContent = SMSContent;
            this.LogID = LogID;
            this.Key = Key;
            this.Mgs = Mgs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUnicomSMSByPhoneIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUnicomSMSByPhoneIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public SendMailService.SendUnicomSMSByPhoneIDResponseBody Body;
        
        public SendUnicomSMSByPhoneIDResponse()
        {
        }
        
        public SendUnicomSMSByPhoneIDResponse(SendMailService.SendUnicomSMSByPhoneIDResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendUnicomSMSByPhoneIDResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendUnicomSMSByPhoneIDResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Mgs;
        
        public SendUnicomSMSByPhoneIDResponseBody()
        {
        }
        
        public SendUnicomSMSByPhoneIDResponseBody(bool SendUnicomSMSByPhoneIDResult, string Mgs)
        {
            this.SendUnicomSMSByPhoneIDResult = SendUnicomSMSByPhoneIDResult;
            this.Mgs = Mgs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SendMailServiceSoapChannel : SendMailService.SendMailServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SendMailServiceSoapClient : System.ServiceModel.ClientBase<SendMailService.SendMailServiceSoap>, SendMailService.SendMailServiceSoap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendMailServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SendMailServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), SendMailServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendMailServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendMailServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendMailServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendMailServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendMailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendMailNoticeResponse> SendMailService.SendMailServiceSoap.SendMailNoticeAsync(SendMailService.SendMailNoticeRequest request)
        {
            return base.Channel.SendMailNoticeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendMailNoticeResponse> SendMailNoticeAsync(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password)
        {
            SendMailService.SendMailNoticeRequest inValue = new SendMailService.SendMailNoticeRequest();
            inValue.Body = new SendMailService.SendMailNoticeRequestBody();
            inValue.Body.Site = Site;
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.From = From;
            inValue.Body.To = To;
            inValue.Body.Cc = Cc;
            inValue.Body.Bcc = Bcc;
            inValue.Body.Subject = Subject;
            inValue.Body.Body = Body;
            inValue.Body.IsBodyHtml = IsBodyHtml;
            inValue.Body.Attachments = Attachments;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((SendMailService.SendMailServiceSoap)(this)).SendMailNoticeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendMailResponse> SendMailService.SendMailServiceSoap.SendMailAsync(SendMailService.SendMailRequest request)
        {
            return base.Channel.SendMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendMailResponse> SendMailAsync(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments)
        {
            SendMailService.SendMailRequest inValue = new SendMailService.SendMailRequest();
            inValue.Body = new SendMailService.SendMailRequestBody();
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.IsBodyHtml = IsBodyHtml;
            inValue.Body.From = From;
            inValue.Body.To = To;
            inValue.Body.Cc = Cc;
            inValue.Body.Bcc = Bcc;
            inValue.Body.Subject = Subject;
            inValue.Body.Body = Body;
            inValue.Body.Attachments = Attachments;
            return ((SendMailService.SendMailServiceSoap)(this)).SendMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendMailSmtpAuthenticationResponse> SendMailService.SendMailServiceSoap.SendMailSmtpAuthenticationAsync(SendMailService.SendMailSmtpAuthenticationRequest request)
        {
            return base.Channel.SendMailSmtpAuthenticationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendMailSmtpAuthenticationResponse> SendMailSmtpAuthenticationAsync(string TeamPwd, bool IsBodyHtml, string From, string To, string Cc, string Bcc, string Subject, string Body, string Attachments, string UserName, string Password)
        {
            SendMailService.SendMailSmtpAuthenticationRequest inValue = new SendMailService.SendMailSmtpAuthenticationRequest();
            inValue.Body = new SendMailService.SendMailSmtpAuthenticationRequestBody();
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.IsBodyHtml = IsBodyHtml;
            inValue.Body.From = From;
            inValue.Body.To = To;
            inValue.Body.Cc = Cc;
            inValue.Body.Bcc = Bcc;
            inValue.Body.Subject = Subject;
            inValue.Body.Body = Body;
            inValue.Body.Attachments = Attachments;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((SendMailService.SendMailServiceSoap)(this)).SendMailSmtpAuthenticationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SimplifySendMailResponse> SendMailService.SendMailServiceSoap.SimplifySendMailAsync(SendMailService.SimplifySendMailRequest request)
        {
            return base.Channel.SimplifySendMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SimplifySendMailResponse> SimplifySendMailAsync(string TeamPwd, bool IsHtml, string FromAddress, string ToAddress, string Subject, string Body)
        {
            SendMailService.SimplifySendMailRequest inValue = new SendMailService.SimplifySendMailRequest();
            inValue.Body = new SendMailService.SimplifySendMailRequestBody();
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.IsHtml = IsHtml;
            inValue.Body.FromAddress = FromAddress;
            inValue.Body.ToAddress = ToAddress;
            inValue.Body.Subject = Subject;
            inValue.Body.Body = Body;
            return ((SendMailService.SendMailServiceSoap)(this)).SimplifySendMailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendEmailInsertQueueResponse> SendMailService.SendMailServiceSoap.SendEmailInsertQueueAsync(SendMailService.SendEmailInsertQueueRequest request)
        {
            return base.Channel.SendEmailInsertQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendEmailInsertQueueResponse> SendEmailInsertQueueAsync(string Site, string TeamPwd, string From, string To, string Cc, string Bcc, string Subject, string Body, bool IsBodyHtml, string Attachments, string UserName, string Password)
        {
            SendMailService.SendEmailInsertQueueRequest inValue = new SendMailService.SendEmailInsertQueueRequest();
            inValue.Body = new SendMailService.SendEmailInsertQueueRequestBody();
            inValue.Body.Site = Site;
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.From = From;
            inValue.Body.To = To;
            inValue.Body.Cc = Cc;
            inValue.Body.Bcc = Bcc;
            inValue.Body.Subject = Subject;
            inValue.Body.Body = Body;
            inValue.Body.IsBodyHtml = IsBodyHtml;
            inValue.Body.Attachments = Attachments;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((SendMailService.SendMailServiceSoap)(this)).SendEmailInsertQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendMobileNoticeResponse> SendMailService.SendMailServiceSoap.SendMobileNoticeAsync(SendMailService.SendMobileNoticeRequest request)
        {
            return base.Channel.SendMobileNoticeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendMobileNoticeResponse> SendMobileNoticeAsync(string Site, string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body)
        {
            SendMailService.SendMobileNoticeRequest inValue = new SendMailService.SendMobileNoticeRequest();
            inValue.Body = new SendMailService.SendMobileNoticeRequestBody();
            inValue.Body.Site = Site;
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.FromEmployeeID = FromEmployeeID;
            inValue.Body.ToEmployeeID = ToEmployeeID;
            inValue.Body.Body = Body;
            return ((SendMailService.SendMailServiceSoap)(this)).SendMobileNoticeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendSMSNoticeResponse> SendMailService.SendMailServiceSoap.SendSMSNoticeAsync(SendMailService.SendSMSNoticeRequest request)
        {
            return base.Channel.SendSMSNoticeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendSMSNoticeResponse> SendSMSNoticeAsync(string TeamPwd, string FromEmployeeID, string ToEmployeeID, string Body)
        {
            SendMailService.SendSMSNoticeRequest inValue = new SendMailService.SendSMSNoticeRequest();
            inValue.Body = new SendMailService.SendSMSNoticeRequestBody();
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.FromEmployeeID = FromEmployeeID;
            inValue.Body.ToEmployeeID = ToEmployeeID;
            inValue.Body.Body = Body;
            return ((SendMailService.SendMailServiceSoap)(this)).SendSMSNoticeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendSMSByPhoneIDResponse> SendMailService.SendMailServiceSoap.SendSMSByPhoneIDAsync(SendMailService.SendSMSByPhoneIDRequest request)
        {
            return base.Channel.SendSMSByPhoneIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendSMSByPhoneIDResponse> SendSMSByPhoneIDAsync(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string Mgs)
        {
            SendMailService.SendSMSByPhoneIDRequest inValue = new SendMailService.SendSMSByPhoneIDRequest();
            inValue.Body = new SendMailService.SendSMSByPhoneIDRequestBody();
            inValue.Body.Site = Site;
            inValue.Body.Unit = Unit;
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.PhoneID = PhoneID;
            inValue.Body.SMSContent = SMSContent;
            inValue.Body.Mgs = Mgs;
            return ((SendMailService.SendMailServiceSoap)(this)).SendSMSByPhoneIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendSMSByPhoneIDOrderResponse> SendMailService.SendMailServiceSoap.SendSMSByPhoneIDOrderAsync(SendMailService.SendSMSByPhoneIDOrderRequest request)
        {
            return base.Channel.SendSMSByPhoneIDOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendSMSByPhoneIDOrderResponse> SendSMSByPhoneIDOrderAsync(string Site, string Unit, string TeamPwd, string PhoneID, string SMSContent, string OrderTime, string Mgs)
        {
            SendMailService.SendSMSByPhoneIDOrderRequest inValue = new SendMailService.SendSMSByPhoneIDOrderRequest();
            inValue.Body = new SendMailService.SendSMSByPhoneIDOrderRequestBody();
            inValue.Body.Site = Site;
            inValue.Body.Unit = Unit;
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.PhoneID = PhoneID;
            inValue.Body.SMSContent = SMSContent;
            inValue.Body.OrderTime = OrderTime;
            inValue.Body.Mgs = Mgs;
            return ((SendMailService.SendMailServiceSoap)(this)).SendSMSByPhoneIDOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendSMSByEmployeeIDResponse> SendMailService.SendMailServiceSoap.SendSMSByEmployeeIDAsync(SendMailService.SendSMSByEmployeeIDRequest request)
        {
            return base.Channel.SendSMSByEmployeeIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendSMSByEmployeeIDResponse> SendSMSByEmployeeIDAsync(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string Mgs)
        {
            SendMailService.SendSMSByEmployeeIDRequest inValue = new SendMailService.SendSMSByEmployeeIDRequest();
            inValue.Body = new SendMailService.SendSMSByEmployeeIDRequestBody();
            inValue.Body.Site = Site;
            inValue.Body.Unit = Unit;
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.ToEmployeeID = ToEmployeeID;
            inValue.Body.SMSContent = SMSContent;
            inValue.Body.Mgs = Mgs;
            return ((SendMailService.SendMailServiceSoap)(this)).SendSMSByEmployeeIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendSMSByEmployeeIDOrderResponse> SendMailService.SendMailServiceSoap.SendSMSByEmployeeIDOrderAsync(SendMailService.SendSMSByEmployeeIDOrderRequest request)
        {
            return base.Channel.SendSMSByEmployeeIDOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendSMSByEmployeeIDOrderResponse> SendSMSByEmployeeIDOrderAsync(string Site, string Unit, string TeamPwd, string ToEmployeeID, string SMSContent, string OrderTime, string Mgs)
        {
            SendMailService.SendSMSByEmployeeIDOrderRequest inValue = new SendMailService.SendSMSByEmployeeIDOrderRequest();
            inValue.Body = new SendMailService.SendSMSByEmployeeIDOrderRequestBody();
            inValue.Body.Site = Site;
            inValue.Body.Unit = Unit;
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.ToEmployeeID = ToEmployeeID;
            inValue.Body.SMSContent = SMSContent;
            inValue.Body.OrderTime = OrderTime;
            inValue.Body.Mgs = Mgs;
            return ((SendMailService.SendMailServiceSoap)(this)).SendSMSByEmployeeIDOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendMailService.SendUnicomSMSByPhoneIDResponse> SendMailService.SendMailServiceSoap.SendUnicomSMSByPhoneIDAsync(SendMailService.SendUnicomSMSByPhoneIDRequest request)
        {
            return base.Channel.SendUnicomSMSByPhoneIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendMailService.SendUnicomSMSByPhoneIDResponse> SendUnicomSMSByPhoneIDAsync(string Site, string TeamName, string TeamPwd, string Unit, string PhoneID, string SMSContent, string LogID, string Key, string Mgs)
        {
            SendMailService.SendUnicomSMSByPhoneIDRequest inValue = new SendMailService.SendUnicomSMSByPhoneIDRequest();
            inValue.Body = new SendMailService.SendUnicomSMSByPhoneIDRequestBody();
            inValue.Body.Site = Site;
            inValue.Body.TeamName = TeamName;
            inValue.Body.TeamPwd = TeamPwd;
            inValue.Body.Unit = Unit;
            inValue.Body.PhoneID = PhoneID;
            inValue.Body.SMSContent = SMSContent;
            inValue.Body.LogID = LogID;
            inValue.Body.Key = Key;
            inValue.Body.Mgs = Mgs;
            return ((SendMailService.SendMailServiceSoap)(this)).SendUnicomSMSByPhoneIDAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendMailServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SendMailServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SendMailServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://qsmcoaap2.rsquanta.com/SMS/SendMailService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SendMailServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://qsmcoaap2.rsquanta.com/SMS/SendMailService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SendMailServiceSoap,
            
            SendMailServiceSoap12,
        }
    }
}
